openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: 'http://payment.bak.ru'
    description: Prod URL
  - url: 'https://payment-qa.bak.ru'
    description: Test URL
tags:
  - name: ClientPaymentController
    description: Методы для обработки запросов на платежи от клиентов
paths:
  /api/payout:
    post:
      summary: Произвести выплату на карту клиента
      operationId: makePayout
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PayoutRequest'
            examples: {}
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PayoutResponse'
      x-internal: false
      description: Описание метода бла бла бла
      tags:
        - ClientPaymentController
  /api/payout/status:
    post:
      tags:
        - ClientPaymentController
      summary: Получить статус по выплате
      operationId: getStatus
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StatusRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
components:
  schemas:
    StatusRequest:
      required:
        - extRequestID
      type: object
      properties:
        extRequestID:
          type: string
          description: Идентификатор запроса на выплату
      description: Получение статуса выплаты
    StatusResponse:
      required:
        - status
      type: object
      properties:
        status:
          type: string
          description: Статус выплаты
          enum:
            - success
            - process
            - failed
      description: Ответ на запрос статуса
    PayoutRequest:
      required:
        - amount
        - cardPan
        - clientId
        - extRequestID
      type: object
      properties:
        cardPan:
          type: string
          description: Номер карты
        clientId:
          type: string
          description: Идентификатор клиента (номер телефона)
        amount:
          type: number
          description: Сумма перевода в рублях
        extRequestID:
          type: string
          description: ID запроса на выплату
      description: Данные для выплаты
    PayoutResponse:
      required:
        - status
      type: object
      properties:
        status:
          type: string
          description: Статус выплаты
          enum:
            - success
            - process
            - failed
      description: Ответ на произведение выплаты
  securitySchemes: {}
